FROM php:7.1-apache
RUN apt-get update && apt-get install -y \
    libpq-dev
RUN apt-get install -y unixodbc-dev
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gnupg \
        curl \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y --no-install-recommends \
        msodbcsql17
RUN docker-php-ext-install pdo pdo_pgsql
RUN pecl install sqlsrv-5.6.1 pdo_sqlsrv-5.6.1 \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv
COPY index.php /var/www/html/
RUN echo "extension=sqlsrv.so" >> /usr/local/etc/php/php.ini \
    && echo "extension=pdo_sqlsrv.so" >> /usr/local/etc/php/php.ini
WORKDIR /var/www/html
EXPOSE 80
CMD ["apache2-foreground"]
