FROM mcr.microsoft.com/mssql/server:2019-latest
ENV ACCEPT_EULA=Y \
    SA_PASSWORD=Un!q@to2023
EXPOSE 1433
COPY init.sql /docker-entrypoint-initdb.d/
ENTRYPOINT ["/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Un!q@to2023", "-d", "master", "-i", "/docker-entrypoint-initdb.d/init.sql"]
# CMD ["/opt/mssql/bin/sqlservr"]
# CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Un!q@to2023 -d master -i init.sql
