FROM php:7.1-apache

# PostgreSQL için gerekli paketleri yükle
RUN apt-get update && apt-get install -y \
    libpq-dev

# unixODBC-dev paketini yükle
RUN apt-get install -y unixodbc-dev

# Microsoft ODBC Sürücüsü'nü yükle
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gnupg \
        curl \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y --no-install-recommends \
        msodbcsql17

# PDO PostgreSQL sürücüsünü etkinleştir
RUN docker-php-ext-install pdo pdo_pgsql

# SQL Server sürücülerini yükle ve etkinleştir
RUN pecl install sqlsrv-5.6.1 pdo_sqlsrv-5.6.1 \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv

# PHP dosyasını kopyala
COPY index.php /var/www/html/

# PHP konfigürasyon dosyasına sürücülerin eklenmesi
RUN echo "extension=sqlsrv.so" >> /usr/local/etc/php/php.ini \
    && echo "extension=pdo_sqlsrv.so" >> /usr/local/etc/php/php.ini

# Çalışma dizinini ayarla
WORKDIR /var/www/html

# Portu aç
EXPOSE 80

# Apache'yi başlat
CMD ["apache2-foreground"]
