version: '3'

services:
  mssql-container:
    build:
      context: .
      dockerfile: Dockerfile-mssql
    environment:
      SA_PASSWORD: "Un!q@to2023"
    ports:
      - "1433:1433"

  api-container:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - "80:80"
    depends_on:
      - mssql-container
